### ISSUE TITLE
Some web pages have a transparent background issue in wexond

### ISSUE THREAD

**Issue by BlobCodes** [wexond/browser-base#362]
**Bug description**
Some web pages seem to have a transparent background. These pages have an issue with the browser not blanking the window after switching to another tab.

**To Reproduce**
Go to a site using a transparent background (ex. [https://materializecss.com/](https://materializecss.com/) )

**Expected behavior**
The page has a white background.

**Screenshots**
![Screenshot_20191122_150241](https://user-images.githubusercontent.com/14961554/69432312-c48b9380-0d39-11ea-823c-0faf04a044dc.png)

**Details:**
 - Operating System: Manjaro Linux
 - Wexond version: 4.0.0-nightly.9
 - Last known working Wexond version: 3.1.0

**Additional context**
Could be an Electron issue.

**Comment by sentialx** [comment]
The website behind your current website is still visible, because I broke destroying `webContents`. It has been fixed already and the fix should be present in the next nightly release. However, when on dark mode, if the website has no background-color specified, it'll be transparent. That's related to an Electron issue https://github.com/electron/electron/issues/20447.

**Comment by xylobol** [comment]
I ran into a similar issue while working on a similar project. This isn't really an Electron bug - in fact, Electron is doing exactly what it's supposed to and making the WebContents' background transparent. The solution is to create a large, blank surface in the Electron app's HTML, positioned where the BrowserView would normally be. 

Edit - January 3rd, 2020, 23:04 MST
I've just noticed that it's setBackgroundColor() not working as well. My bad. This should still be a decent workaround, however.
