### ISSUE TITLE
Condense URL bar with titlebar like before

### ISSUE THREAD

**Issue by leonewt0n** [wexond/browser-base#454]
**Bug description**
In the New 5.0 branch, the tabs and titlebar are separate like in chrome. I liked the old way where they were condensed. 

**To Reproduce**
Use 5.0 

**Expected behavior**
Tabs in titlebar. 

**Details:**
 - Operating System:  Fedora Silverblue 32
 - Wexond version: 5.0
 - Last known working Wexond version: 4.0

**Additional context**
Maybe you could add it as an option in the settings menu?

**Comment by sentialx** [comment]
If that wouldn't bring me a huge maintenance burden with 2 address bar implementations then I'm okay with it. I will need to take this into my consideration.

**Comment by i3d** [comment]
What a terrible idea of having it look like Chrome and taking extra content space out for a thing that can totally dynamically displayed. It WAS such a nice browser, but now, sorry, I wouldn't use it anymore (otherwise, I am stuck at 4.0)

BTW, Did you know Min browser? Probably something we can learn...

**Comment by sentialx** [comment]
@i3d @leocodeninja Released in v5.0.0

**Comment by i3d** [comment]
wonderful, thank you, so much!!
